---
title: 猫ミームジェネレータ
hero_image: images/banner.png
description: かっこいい猫のミームを作って友達と共有しましょう
original_url: https://www.raspberrypi.org/learning/cat-meme-generator/
theme: orange
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: 動物
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: はじめに
  - 
    title: 必要なもの
  - 
    title: Webページを作成する
  - 
    title: 画像とテキストを取得する
  - 
    title: ミームを構築する
  - 
    title: テキストを表示する
  - 
    title: 画像を表示する
  - 
    title: 完成したコード
  - 
    title: チャレンジ
