---
title: Gerador de Memes
hero_image: images/banner.png
description: Faça memes legais de gatos para compartilhar com seus amigos
original_url: https://www.raspberrypi.org/learning/cat-meme-generator/
theme: orange
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: animals
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 01-11-2017
steps:
  - title: Introdução
  - title: O que você vai precisar
  - title: Crie uma página da web
  - title: Obtendo a foto e o texto
  - title: Construa o meme
  - title: Exibir o texto
  - title: Exibir a imagem
  - title: O código finalizado
  - title: Desafio
