---
title: Generador de mem de gat
hero_image: images/banner.png
description: Fes fantàstics mems de gat per compartir amb els teus amics
original_url: https://www.raspberrypi.org/learning/cat-meme-generator/
theme: taronja
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: animals
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projectes
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Crea una pàgina web
  - 
    title: Obtenció de la imatge i el text
    completion:
      - engaged
  - 
    title: Construeix el mem
  - 
    title: Mostra el text
  - 
    title: Mostra la imatge
  - 
    title: El codi acabat
    completion:
      - internal
  - 
    title: Repte
