---
title: 貓咪迷因製造機
hero_image: images/banner.png
description: 製作酷炫的貓咪迷因與你的朋友分享
original_url: https://www.raspberrypi.org/learning/cat-meme-generator/
theme: orange
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: animals
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-11-01
steps:
- title: 介紹
- title: 你會需要
  completion: engaged
- title: 建立一個頁面
- title: 取得圖片和文字
- title: 建立一個迷因
- title: 顯示文字
- title: 顯示圖片
- title: 最終的程式碼
  completion: internal
- title: 挑戰
