---
title: Générateur de mèmes de chat
hero_image: images/banner.png
description: Crée des mèmes de chat sympas à partager avec tes amis
original_url: https://www.raspberrypi.org/learning/cat-meme-generator/
theme: orange
duration: 2
ingredient: false
listed: true
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: animals
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-11-01
steps:
- title: Introduction
- title: Ce dont tu auras besoin
  completion: engaged
- title: Créer une page Web
- title: Obtenir l'image et le texte
- title: Construire le mème
- title: Afficher le texte
- title: Afficher l'image
- title: Le code terminé
  completion: internal
- title: Défi
